// Mocks generated by Mockito 5.4.6 from annotations
// in work_rhythm/test/domain/usecases/get_daily_report_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:work_rhythm/domain/entities/distraction_entry.dart' as _i3;
import 'package:work_rhythm/domain/entities/learning_goal.dart' as _i4;
import 'package:work_rhythm/domain/entities/learning_session.dart' as _i5;
import 'package:work_rhythm/domain/entities/work_session.dart' as _i2;
import 'package:work_rhythm/domain/repositories/i_distraction_repository.dart'
    as _i8;
import 'package:work_rhythm/domain/repositories/i_learning_repository.dart'
    as _i9;
import 'package:work_rhythm/domain/repositories/i_work_session_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkSession_0 extends _i1.SmartFake implements _i2.WorkSession {
  _FakeWorkSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDistractionEntry_1 extends _i1.SmartFake
    implements _i3.DistractionEntry {
  _FakeDistractionEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLearningGoal_2 extends _i1.SmartFake implements _i4.LearningGoal {
  _FakeLearningGoal_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLearningSession_3 extends _i1.SmartFake
    implements _i5.LearningSession {
  _FakeLearningSession_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IWorkSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWorkSessionRepository extends _i1.Mock
    implements _i6.IWorkSessionRepository {
  MockIWorkSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.WorkSession> startSession() => (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [],
        ),
        returnValue: _i7.Future<_i2.WorkSession>.value(_FakeWorkSession_0(
          this,
          Invocation.method(
            #startSession,
            [],
          ),
        )),
      ) as _i7.Future<_i2.WorkSession>);

  @override
  _i7.Future<_i2.WorkSession> pauseSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseSession,
          [sessionId],
        ),
        returnValue: _i7.Future<_i2.WorkSession>.value(_FakeWorkSession_0(
          this,
          Invocation.method(
            #pauseSession,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i2.WorkSession>);

  @override
  _i7.Future<_i2.WorkSession> resumeSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resumeSession,
          [sessionId],
        ),
        returnValue: _i7.Future<_i2.WorkSession>.value(_FakeWorkSession_0(
          this,
          Invocation.method(
            #resumeSession,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i2.WorkSession>);

  @override
  _i7.Future<_i2.WorkSession> stopSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopSession,
          [sessionId],
        ),
        returnValue: _i7.Future<_i2.WorkSession>.value(_FakeWorkSession_0(
          this,
          Invocation.method(
            #stopSession,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i2.WorkSession>);

  @override
  _i7.Future<_i2.WorkSession?> getActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i7.Future<_i2.WorkSession?>.value(),
      ) as _i7.Future<_i2.WorkSession?>);

  @override
  _i7.Future<List<_i2.WorkSession>> getSessionsForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionsForDate,
          [date],
        ),
        returnValue:
            _i7.Future<List<_i2.WorkSession>>.value(<_i2.WorkSession>[]),
      ) as _i7.Future<List<_i2.WorkSession>>);

  @override
  _i7.Future<void> updateNetSeconds(
    int? sessionId,
    int? netSeconds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNetSeconds,
          [
            sessionId,
            netSeconds,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [IDistractionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDistractionRepository extends _i1.Mock
    implements _i8.IDistractionRepository {
  MockIDistractionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.DistractionEntry> addDistraction({
    required int? sessionId,
    required _i3.DistractionCategory? category,
    required int? durationSeconds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDistraction,
          [],
          {
            #sessionId: sessionId,
            #category: category,
            #durationSeconds: durationSeconds,
          },
        ),
        returnValue:
            _i7.Future<_i3.DistractionEntry>.value(_FakeDistractionEntry_1(
          this,
          Invocation.method(
            #addDistraction,
            [],
            {
              #sessionId: sessionId,
              #category: category,
              #durationSeconds: durationSeconds,
            },
          ),
        )),
      ) as _i7.Future<_i3.DistractionEntry>);

  @override
  _i7.Future<List<_i3.DistractionEntry>> getDistractionsForSession(
          int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistractionsForSession,
          [sessionId],
        ),
        returnValue: _i7.Future<List<_i3.DistractionEntry>>.value(
            <_i3.DistractionEntry>[]),
      ) as _i7.Future<List<_i3.DistractionEntry>>);

  @override
  _i7.Future<List<_i3.DistractionEntry>> getDistractionsForDate(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistractionsForDate,
          [date],
        ),
        returnValue: _i7.Future<List<_i3.DistractionEntry>>.value(
            <_i3.DistractionEntry>[]),
      ) as _i7.Future<List<_i3.DistractionEntry>>);

  @override
  _i7.Future<int> getTotalDistractionSeconds(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalDistractionSeconds,
          [sessionId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
}

/// A class which mocks [ILearningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILearningRepository extends _i1.Mock
    implements _i9.ILearningRepository {
  MockILearningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.LearningGoal>> getActiveGoals() => (super.noSuchMethod(
        Invocation.method(
          #getActiveGoals,
          [],
        ),
        returnValue:
            _i7.Future<List<_i4.LearningGoal>>.value(<_i4.LearningGoal>[]),
      ) as _i7.Future<List<_i4.LearningGoal>>);

  @override
  _i7.Future<_i4.LearningGoal> createGoal({
    required String? name,
    required int? targetMinutes,
    DateTime? deadline,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGoal,
          [],
          {
            #name: name,
            #targetMinutes: targetMinutes,
            #deadline: deadline,
            #description: description,
          },
        ),
        returnValue: _i7.Future<_i4.LearningGoal>.value(_FakeLearningGoal_2(
          this,
          Invocation.method(
            #createGoal,
            [],
            {
              #name: name,
              #targetMinutes: targetMinutes,
              #deadline: deadline,
              #description: description,
            },
          ),
        )),
      ) as _i7.Future<_i4.LearningGoal>);

  @override
  _i7.Future<_i5.LearningSession> startSession(int? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [goalId],
        ),
        returnValue:
            _i7.Future<_i5.LearningSession>.value(_FakeLearningSession_3(
          this,
          Invocation.method(
            #startSession,
            [goalId],
          ),
        )),
      ) as _i7.Future<_i5.LearningSession>);

  @override
  _i7.Future<_i5.LearningSession> stopSession(int? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopSession,
          [sessionId],
        ),
        returnValue:
            _i7.Future<_i5.LearningSession>.value(_FakeLearningSession_3(
          this,
          Invocation.method(
            #stopSession,
            [sessionId],
          ),
        )),
      ) as _i7.Future<_i5.LearningSession>);

  @override
  _i7.Future<_i5.LearningSession?> getActiveSession() => (super.noSuchMethod(
        Invocation.method(
          #getActiveSession,
          [],
        ),
        returnValue: _i7.Future<_i5.LearningSession?>.value(),
      ) as _i7.Future<_i5.LearningSession?>);

  @override
  _i7.Future<int> getCompletedMinutesForGoal(int? goalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedMinutesForGoal,
          [goalId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);
}
